// Auto-generated by closure-dts-externs

var VERSION;
var app;
var bootstrap;
var counter;
var debugHelper;
var plugin;
var shutdown;
var tempVar;

app.destroy;
app.env;
app.env.DATA_PATH;
app.init;
app.run;

plugin.activate;
plugin.deactivate;
plugin.reload;

function Config() {}
Config.prototype.debug;
Config.prototype.options;
Config.prototype.options.level;
Config.prototype.options.verbose;

function EventEmitter() {}
EventEmitter.prototype.emit;
EventEmitter.prototype.on;

function Logger() {}
Logger.prototype.error;
Logger.prototype.log;
Logger.prototype.warn;

function Timer() {}
Timer.prototype.start;
Timer.prototype.stop;

function Util() {}
Util.prototype.format;
