import { writeFileSync } from 'node:fs';
import ts from 'typescript';

/**
 * Options for generating Closure Compiler externs.
 */
export interface GenerateExternsOptions {
    /**
     * Path(s) to the `.d.ts` entry file(s).
     *
     * @example
     * ```ts
     * // Single entry
     * 'path/to/typings.d.ts'
     * // Multiple entries
     * ['types/api.d.ts', 'types/cloud.d.ts']
     * ```
     */
    dtsEntry: string | string[];

    /**
     * Path to write the generated externs file.
     * If omitted, the externs content is returned as a string without writing to disk.
     */
    outputPath?: string;

    /**
     * Filter which source files to process.
     * By default, all files except TypeScript built-in libs are processed.
     *
     * @example
     * ```ts
     * // Only process files from a specific package
     * fileFilter: (fileName) => fileName.includes('my-typings')
     * ```
     */
    fileFilter?: (fileName: string) => boolean;

    /**
     * Global declaration names to exclude from output.
     * Supports simple wildcard patterns with `*`.
     *
     * @example
     * ```ts
     * excludeGlobals: ['console', 'set*', 'clear*', 'require', 'module', 'exports']
     * ```
     */
    excludeGlobals?: string[];
}

function getNodeName(node: ts.Node): string | undefined {
    const name = (node as ts.NamedDeclaration).name;
    if (name && ts.isIdentifier(name)) {
        return name.text;
    }
    return undefined;
}

function collectMembers(node: ts.Node, prefix = ''): Set<string> {
    const members = new Set<string>();
    ts.forEachChild(node, child => {
        const memberName = getNodeName(child);
        if (!memberName) return;
        const path = prefix ? `${prefix}.${memberName}` : memberName;
        members.add(path);
        // Recursively expand inline object type literals (e.g. `env: { USER_DATA_PATH: string }`)
        if ((ts.isPropertySignature(child) || ts.isPropertyDeclaration(child)) && child.type && ts.isTypeLiteralNode(child.type)) {
            for (const nested of collectMembers(child.type, path)) {
                members.add(nested);
            }
        }
    });
    return members;
}

/**
 * Resolve the type name from a type annotation like `SomeNamespace.TypeName` or `TypeName`.
 */
function resolveTypeName(typeNode: ts.TypeNode): string | undefined {
    if (ts.isTypeReferenceNode(typeNode)) {
        const typeName = typeNode.typeName;
        if (ts.isQualifiedName(typeName)) {
            // e.g. WechatMinigame.Wx → 'Wx'
            return typeName.right.text;
        }
        // typeName is Identifier (e.g. `declare const x: Foo`)
        return (typeName as ts.Identifier).text;
    }
    return undefined;
}

function visitNamespace(nsDecl: ts.ModuleDeclaration, interfaceMembers: Map<string, Set<string>>): void {
    const body = nsDecl.body as ts.ModuleBody;
    ts.forEachChild(body, child => {
        if (ts.isModuleDeclaration(child) && child.name && ts.isIdentifier(child.name)) {
            visitNamespace(child, interfaceMembers);
        } else if (ts.isInterfaceDeclaration(child)) {
            const existing = interfaceMembers.get(child.name.text);
            const members = collectMembers(child);
            if (existing) {
                // Merge augmented interface declarations
                for (const m of members) {
                    existing.add(m);
                }
            } else {
                interfaceMembers.set(child.name.text, members);
            }
        } else if (ts.isClassDeclaration(child)) {
            const name = child.name?.text;
            if (!name) return;
            interfaceMembers.set(name, collectMembers(child));
        }
    });
}

function matchesPattern(name: string, pattern: string): boolean {
    if (!pattern.includes('*')) {
        return name === pattern;
    }
    const regex = new RegExp(`^${pattern.replace(/\*/g, '.*')}$`);
    return regex.test(name);
}

function isExcluded(name: string, excludeGlobals: string[]): boolean {
    return excludeGlobals.some(pattern => matchesPattern(name, pattern));
}

interface GlobalVarInfo {
    varName: string;
    typeName?: string;
}

function buildExternsContent(
    globalVars: GlobalVarInfo[],
    globalFunctions: Set<string>,
    interfaceMembers: Map<string, Set<string>>,
): string {
    const lines: string[] = [
        '// Auto-generated by closure-dts-externs',
        '',
    ];

    // Associate global variables with their interface members
    const globalObjectMembers = new Map<string, Set<string>>();
    for (const { varName, typeName } of globalVars) {
        if (typeName && interfaceMembers.has(typeName)) {
            globalObjectMembers.set(varName, interfaceMembers.get(typeName) as Set<string>);
            interfaceMembers.delete(typeName);
        }
    }

    // 1. Global variable declarations
    const allGlobalNames = new Set<string>();
    for (const { varName } of globalVars) {
        allGlobalNames.add(varName);
    }
    for (const fn of globalFunctions) {
        allGlobalNames.add(fn);
    }

    for (const name of [...allGlobalNames].sort()) {
        lines.push(`var ${name};`);
    }
    lines.push('');

    // 2. Global object members
    const sortedGlobalObjects = [...globalObjectMembers].sort(([a], [b]) => a.localeCompare(b));
    for (const [varName, members] of sortedGlobalObjects) {
        for (const member of [...members].sort()) {
            lines.push(`${varName}.${member};`);
        }
        lines.push('');
    }

    // 3. Remaining interface/class prototype declarations
    if (interfaceMembers.size > 0) {
        const sorted = [...interfaceMembers].sort(([a], [b]) => a.localeCompare(b));
        for (const [ifaceName, members] of sorted) {
            lines.push(`function ${ifaceName}() {}`);
            for (const member of [...members].sort()) {
                lines.push(`${ifaceName}.prototype.${member};`);
            }
            lines.push('');
        }
    }

    return lines.join('\n');
}

const defaultFileFilter = (fileName: string): boolean => !fileName.includes('/typescript/lib/');

/**
 * Generate Closure Compiler externs from `.d.ts` type definitions.
 *
 * @example
 * ```ts
 * // Write to file
 * generateExterns({ dtsEntry: 'path/to/typings.d.ts', outputPath: 'externs.js' });
 *
 * // Get as string
 * const content = generateExterns({ dtsEntry: 'path/to/typings.d.ts' });
 * ```
 */
export function generateExterns(options: GenerateExternsOptions): string {
    const {
        dtsEntry,
        outputPath,
        fileFilter = defaultFileFilter,
        excludeGlobals = [],
    } = options;

    const interfaceMembers = new Map<string, Set<string>>();
    const globalVars: GlobalVarInfo[] = [];
    const globalFunctions = new Set<string>();

    const program = ts.createProgram({
        rootNames: Array.isArray(dtsEntry) ? dtsEntry : [dtsEntry],
        options: {
            // Prevent auto-inclusion of @types/* packages, only process dtsEntry and its explicit references
            types: [],
        },
    });

    for (const sourceFile of program.getSourceFiles()) {
        if (!fileFilter(sourceFile.fileName)) continue;
        ts.forEachChild(sourceFile, node => {
            if (ts.isModuleDeclaration(node) && node.name && ts.isIdentifier(node.name)) {
                visitNamespace(node, interfaceMembers);
            } else if (ts.isVariableStatement(node)) {
                // declare const/var/let xxx: Type
                for (const decl of node.declarationList.declarations) {
                    const varName = getNodeName(decl);
                    if (!varName || isExcluded(varName, excludeGlobals)) continue;
                    const typeName = decl.type ? resolveTypeName(decl.type) : undefined;
                    globalVars.push({ varName, typeName });
                }
            } else if (ts.isFunctionDeclaration(node) && node.name) {
                const fnName = getNodeName(node);
                if (fnName && !isExcluded(fnName, excludeGlobals)) {
                    globalFunctions.add(fnName);
                }
            } else if (ts.isInterfaceDeclaration(node)) {
                const existing = interfaceMembers.get(node.name.text);
                const members = collectMembers(node);
                if (existing) {
                    for (const m of members) {
                        existing.add(m);
                    }
                } else {
                    interfaceMembers.set(node.name.text, members);
                }
            } else if (ts.isClassDeclaration(node) && node.name) {
                interfaceMembers.set(node.name.text, collectMembers(node));
            }
        });
    }

    const content = buildExternsContent(globalVars, globalFunctions, interfaceMembers);

    if (outputPath) {
        writeFileSync(outputPath, content);

        const totalMembers = [...interfaceMembers.values()].reduce((sum, m) => sum + m.size, 0);
        console.info(`Generated ${outputPath}`);
        console.info(`  global vars: ${globalVars.length}, global functions: ${globalFunctions.size}`);
        console.info(`  interface/class types: ${interfaceMembers.size}, total members: ${totalMembers}`);
    }

    return content;
}
